Repository atlp-rwanda/e-comm-team-axel25-fe, pull requests merged in 2023-03, with the labels that each got.

#2 add sass pre-processing on the application.
  package.json
  pnpm-lock.yaml
  src/assets/styles/global.scss
  src/index.tsx
  webpack/webpack.common.js
Labels: enhancement

#4 chore: setting up react-router-dom-#184749803
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/Routes/index.ts
  src/Routes/sample.routes.tsx
  src/lib/Router/AppRouter.tsx
  src/lib/index.ts
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/NotFound.tsx
Labels: Enhancement

#7 #184749810 ch: Configure storybook for component development
  .eslintrc.js
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Introduction.mdx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: Chore, Ready for Review

#6 #184749809 chore:setup git action
  .github/workflows/index.yml
  .gitignore
Labels: Ready for Review

#8 ch(jest): setup jest tests [#184749807]
  README.md
  jest.config.js
  package.json
  pnpm-lock.yaml
  src/__tests__/Toggle.spec.tsx
  src/__tests__/calculator.spec.ts
  src/components/Toggle.tsx
  src/components/calculator.ts
  src/context/__tests__/test.spec.ts
  src/hooks/__tests__/test.spec.ts
  src/layouts/__tests__/test.spec.ts
  src/lib/__tests__/test.spec.ts
  src/services/__tests__/test.spec.ts
  src/utils/__tests__/test.spec.ts
Labels: Chore, Ready for Review

#13 chore: adding git hooks
  .github/workflows/index.yml
  .husky/pre-commit
  .husky/pre-push
  package.json
  pnpm-lock.yaml
Labels: Ready for Review, changes fixed

#11 ch: add tailwind css 🦚
  .husky/pre-commit
  .husky/pre-push
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/App.tsx
  src/Routes/index.ts
  src/assets/styles/_global.scss
  src/assets/styles/global.scss
  src/components/Counter.tsx
  src/components/ui/Button.tsx
  src/index.tsx
  src/lib/class/ClassNames.tsx
  src/lib/index.ts
  src/pages/Home.tsx
  src/reducers/index.ts
  tailwind.config.js
  webpack/webpack.common.js
Labels: Ready for Review

#25 ch: add button component 👆🏽
  .gitignore
  .npmrc
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/assets/styles/_global.scss
  src/assets/styles/components/_button.scss
  src/components/Counter.tsx
  src/components/ui/Button.stories.tsx
  src/components/ui/Button.tsx
  src/index.tsx
  src/pages/Home.tsx
  src/utils/types/button.types.ts
  src/utils/types/index.ts
  tailwind.config.js
  webpack/webpack.common.js
Labels: Ready for Review, changes fixed
