Repository atlp-rwanda/e-comm-team-axel25-fe, pull requests merged in 2023-04, with the labels that each got.

#23 fx: add codeclimate test coverage and Maintainability badge #184749806
  .github/workflows/index.yml
  README.md
Labels: Help wanted, Needs Peer Review

#45 ft: add star ratings component [#44]
  .eslintrc.js
  package.json
  pnpm-lock.yaml
  src/Routes/index.ts
  src/Routes/routes.tsx
  src/components/Counter.tsx
  src/components/shared/Button.stories.tsx
  src/components/shared/Button.tsx
  src/components/shared/ButtonGroup.tsx
  src/components/shared/Card.tsx
  src/components/shared/DropDown.tsx
  src/components/shared/Modal.tsx
  src/components/shared/Stars.stories.ts
  src/components/shared/Stars.tsx
  src/components/shared/index.ts
  src/pages/Login.tsx
Labels: Needs Peer Review, Ready for Review

#46 ft: add header 🌉
  .github/workflows/index.yml
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/Routes/routes.tsx
  src/assets/images/index.ts
  src/assets/images/logo.svg
  src/assets/images/placeholder.jpg
  src/assets/styles/_global.scss
  src/components/Avatar.tsx
  src/components/Container.tsx
  src/components/Counter.tsx
  src/components/Navbar.tsx
  src/components/index.ts
  src/components/navbar/Logo.tsx
  src/components/navbar/MenuItem.tsx
  src/components/navbar/Navbar.stories.tsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/Search.tsx
  src/components/navbar/ThemeToggle.tsx
  src/components/navbar/UserMenu.tsx
  src/hooks/index.ts
  src/hooks/useTheme.ts
  src/layouts/Navbar.tsx
  src/layouts/PageContainer.tsx
  src/layouts/Sidebar.tsx
  src/layouts/index.ts
  src/layouts/layout.tsx
  src/lib/Router/AppRouter.tsx
  src/pages/Home.tsx
  src/reducers/index.ts
  src/store.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Introduction.mdx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/utils/types/index.ts
  src/utils/types/router.types.ts
  tailwind.config.js
Labels: Feature, Needs Peer Review

#18 ft: add cart summary card component
  src/assets/icons/padlock.svg
  src/components/shared/CartSummaryCard.stories.tsx
  src/components/shared/CartSummaryCard.tsx
  src/components/shared/index.ts
Labels: Ready for Review

#32 ft: add sold-by card component
  src/components/shared/SoldByCard.stories.tsx
  src/components/shared/SoldByCard.tsx
  src/components/shared/index.ts
Labels: Ready for Review

#56 ft: add single product view 🔍
  pnpm-lock.yaml
  src/components/Heading.tsx
  src/components/index.ts
  src/components/inputs/Counter.tsx
  src/components/products/ProductCard.stories.tsx
  src/components/products/ProductCard.tsx
  src/components/products/ProductImage.tsx
  src/components/products/ProductInfo.tsx
  src/components/shared/Stars.tsx
  src/data/images.ts
  src/data/index.ts
  src/layouts/layout.tsx
  src/pages/Products.tsx
  src/pages/index.ts
  src/utils/types/index.ts
  src/utils/types/product.types.ts
Labels: Feature, Ready for Review

#38 ft: add reviews card component
  src/components/shared/ReviewsCard.stories.tsx
  src/components/shared/ReviewsCard.tsx
  src/components/shared/index.ts
  src/pages/Login.tsx
Labels: Ready for Review, changes fixed

#29 ft-footer-component
  .gitignore
  pnpm-lock.yaml
  src/components/Footer.tsx
  src/components/index.ts
  src/components/shared/footer/Footer.stories.tsx
  src/components/shared/footer/Footer.tsx
  src/components/shared/navbar/Logo.tsx
  src/components/shared/navbar/MenuItem.tsx
  src/components/shared/navbar/Navbar.stories.tsx
  src/components/shared/navbar/Navbar.tsx
  src/components/shared/navbar/Search.tsx
  src/components/shared/navbar/ThemeToggle.tsx
  src/components/shared/navbar/UserMenu.tsx
  src/layouts/layout.tsx
  src/pages/Home.tsx
Labels: Ready for Review

#48 ft: add categories ui & sidebar 🗳️
  package.json
  pnpm-lock.yaml
  src/components/index.ts
  src/components/shared/navbar/Categories.tsx
  src/components/shared/navbar/CategoryBox.tsx
  src/components/shared/navbar/Navbar.tsx
  src/components/shared/navbar/ThemeToggle.tsx
  src/components/shared/navbar/UserMenu.tsx
  src/components/sidebar/ScrollButton.tsx
  src/components/sidebar/SideBar.tsx
  src/components/sidebar/SideBarButton.tsx
  src/components/sidebar/SideBarItem.tsx
  src/components/sidebar/index.ts
  src/data/categories.ts
  src/data/index.ts
  src/hooks/index.ts
  src/hooks/useHomeLogic.ts
  src/hooks/useSideBar.ts
  src/hooks/useTheme.ts
  src/store.ts
Labels: Feature, Ready for Review

#52 ft: add parent/generic modal component 📻
  src/assets/styles/components/_button.scss
  src/components/index.ts
  src/components/shared/Modal.tsx
  src/components/shared/index.ts
  src/components/shared/modals/Modal.stories.tsx
  src/components/shared/modals/Modal.tsx
  src/components/shared/modals/ModalFooter.tsx
  src/components/shared/modals/ModalHeader.tsx
  src/hooks/index.ts
  src/hooks/useModal.ts
Labels: Feature, Changes Requested, changes fixed

#47 ft: add cart item component 🛒
  pnpm-lock.yaml
  src/components/cart/CartDescription.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartStats.tsx
  src/components/shared/CartItem.stories.tsx
  src/components/shared/index.ts
  src/pages/Login.tsx
Labels: Ready for Review, changes fixed

#12 Ft google auth #184749812
  .babelrc
  .env.example
  .eslintrc.js
  .npmrc
  .storybook/preview.ts
  babel.config.js
  package.json
  pnpm-lock.yaml
  public/index.html
  src/assets/favicon.ico
  src/assets/styles/_global.scss
  src/assets/styles/components/button.css
  src/assets/styles/global.css
  src/components/shared/Alert.tsx
  src/components/shared/navbar/UserMenu.tsx
  src/data/constants.ts
  src/data/defaultProducts.json
  src/features/authentication/hooks/useConfirmPassword.ts
  src/features/authentication/hooks/useLogin.ts
  src/features/authentication/hooks/useRegistration.ts
  src/features/authentication/services/getUser.ts
  src/features/authentication/services/login.ts
  src/features/authentication/services/registration.ts
  src/hooks/index.ts
  src/hooks/useGoogleAuth.tsx
  src/images.d.ts
  src/index.tsx
  src/layouts/layout.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/index.ts
  src/reducers/authReducer.ts
  src/services/analytics.ts
  src/services/googleApi.ts
  src/services/index.ts
  src/store.ts
  src/utils/checkEnv.ts
  src/utils/index.ts
  src/utils/types/index.ts
  src/utils/types/user.type.ts
  static/favicon.ico
  tsconfig.json
  webpack/webpack.base.ts
  webpack/webpack.common.js
  webpack/webpack.config.js
  webpack/webpack.dev.js
  webpack/webpack.dev.ts
  webpack/webpack.prod.js
  webpack/webpack.prod.ts
Labels: Ready for Review

#37 ft: add form input field component #36
  package.json
  pnpm-lock.yaml
  src/components/form/FormInput.tsx
  src/components/index.ts
  src/components/inputs/Demo.tsx
  src/components/inputs/Demo2.tsx
  src/components/inputs/InputField.stories.tsx
  src/components/inputs/InputField.tsx
  src/components/shared/Button.tsx
  src/pages/Login.tsx
  src/utils/schemas/index.ts
  src/utils/schemas/login.schema.ts
  src/utils/schemas/product.schema.ts
  src/utils/types/button.types.ts
Labels: Ready for Review
